# Generated by Django 3.2.13 on 2022-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group_setting',
        ),
    ]
